### ISSUE TITLE
changing directory within your script might limit the ability of using relative paths as input.

### ISSUE THREAD

**Issue by awchrist** [tgen/vcfMerger2#11]
https://github.com/tgen/vcfMerger2/blob/1b2f4d4352ac8ceb31c29d63d8505851e8487713/prep_vcfs_somatic/prep_vcf_somatic_functions.sh#L611

Do we need cd in the vcfmerger_prep?

**Comment by ChristopheLegendre** [comment]
You do **not** need;
The only thing you do need is to provide the FULL path to your input data, to the bam file in particular;

_FYI_: I did this `cd` because `prep_vcf_somatic` was an **internal function** not to be called directly;  The `prep` step was designed to be run from its own special directory with **ALL** the inputs already present in that directory;
