### ISSUE TITLE
VCF validation issues with VarDict, Mutect2, and Octopus fields

### ISSUE THREAD

**Issue by denriquez** [tgen/vcfMerger2#22]
vcf-validator from VCFtools v0.1.13 found issues with three info fields within vcfMerger2 VCFs.

Issue 1:
##INFO=<ID=VARDICT_SOR,Number=1,Type=Float,Description="Odds ratio">
The issue with the line above is that the values for VARDICT_SOR seem to be all "inf" and not an actual float.
Possible Solution:
##INFO=<ID=VARDICT_SOR,Number=1,Type=String,Description="Odds ratio">.
Instead of a string type we could keep it as a float and convert all of the "inf" values to "1.0" or "0.99"

Issue 2:
##INFO=<ID=MUTECT2_AS_SB_TABLE,Number=1,Type=String,Description="Allele-specific forward/reverse read counts for strand bias tests. Includes the reference and alleles separated by |.">
The issue with this line is that there are 3 string values and not just one stated by "Number=1". For example, one of the values is "79,126|29,50." Since commas are used as a delimiter to create a list of values, the total number of strings shown in the example is 3.
Possible Solution:
##INFO=<ID=MUTECT2_AS_SB_TABLE,Number=.,Type=String,Description="Allele-specific forward/reverse read counts for strand bias tests. Includes the reference and alleles separated by |.">

Issue 3:
##INFO=<ID=OCTOPUS_AC,Number=A,Type=Integer,Description="Allele count in genotypes for each ALT allele in the same order as listed">
The issue with this one is that the allele count sometimes has values for a secondary alt allele, however, there are no additional alt alleles shown in the ALT field.
Possible Solution:
##INFO=<ID=OCTOPUS_AC,Number=.,Type=Integer,Description="Allele count in genotypes for each ALT allele in the same order as listed">

**Comment by ChristopheLegendre** [comment]
@denriquez  Thanks for pointing these issues to us.
Based on our discussion during the pipeline meeting, we decided that these issues will not be fixed within `vcfMerger2` but will be fixed separately using a script that will take the original VCFs outputted by the variant caller tools (in this case here, `mutect2`, `octopus` and `vardict`)

The question of the fix for `vardict` remains: the only way to fix it is to have a float as value, not `inf`. Modifying the header `number` does not work whatever the value we put in for `number`. 
The fix you proposed for `octopus` and `mutect2` will be the one implemented.

**Comment by ChristopheLegendre** [comment]
A script has been created to fix the mentioned issues within the original tool `vcf`s.
the temporary script name is `make_vcf_up_to_specs.sh` and will be added to the `phoenix` pipeline.
Note: this script does not fix the other potential issues found by `vcf`-validator or any other `vcf` validator because these might already be taken care of by the `vcfMerger2` `prep_vcf` step.

**Comment by ChristopheLegendre** [comment]
no errors have been reported since the fix.
Closing the issue.
If the error occurs again, please reopen the current issue.
